name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: pnpm test
      - run: pnpm lint
      - run: pnpm format:check
      - run: pnpm build
      - run: |
          if [ $GITHUB_REF = "refs/heads/main" ]; then
            echo "Branch is main, publishing package."
            # pnpm publish --access public
          else
            echo "Branch is not main, skipping publish step."
          fi
